#!/bin/bash

FROM=iso-8859-1
TO=UTF-8
ICONV="iconv -f $FROM -t $TO"

# Convert
find aclImdb/train/pos -type f -name "*" | while read fn;
 do
    echo ${fn}
    cp ${fn} ${fn}.bak
    $ICONV < ${fn}.bak > ${fn}
    rm ${fn}.bak
done